### ISSUE TITLE
[Error] Can't start redis server with windows

### ISSUE THREAD

**Issue by leesj8116** [9o-clock/9o-clock-server#30]
# 개요
윈도우 환경에서 `Can't start redis server`  메세지와 함께 Redis 내장 서버 가동에 실패하는 에러입니다.

## 환경 정보
- `os.name` : Windows 11
- `os.arch` : amd64
- Java Version: Eclipse Temurin version 17.0.7
- redis는 시스템에 설치되어있지 않습니다.

## 로그
```log
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedRedisConfig': Invocation of init method failed; nested exception is java.lang.RuntimeException: Can't start redis server. Check logs for details.
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:132) ~[spring-boot-test-2.7.3.jar:2.7.3]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) ~[spring-test-5.3.22.jar:5.3.22]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-5.3.22.jar:5.3.22]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124) ~[spring-test-5.3.22.jar:5.3.22]
	at io.cucumber.spring.TestContextAdaptor.<init>(TestContextAdaptor.java:36) ~[cucumber-spring-7.11.0.jar:7.11.0]
	at io.cucumber.spring.SpringFactory.start(SpringFactory.java:120) ~[cucumber-spring-7.11.0.jar:7.11.0]
	at io.cucumber.core.runner.Runner.buildBackendWorlds(Runner.java:134) ~[cucumber-core-7.11.0.jar:7.11.0]
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:70) ~[cucumber-core-7.11.0.jar:7.11.0]
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.lambda$run$0(PickleRunners.java:151) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:130) ~[cucumber-core-7.11.0.jar:7.11.0]
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23) ~[cucumber-core-7.11.0.jar:7.11.0]
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:130) ~[cucumber-core-7.11.0.jar:7.11.0]
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:148) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) ~[junit-4.13.2.jar:4.13.2]
	at io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:196) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:89) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) ~[junit-4.13.2.jar:4.13.2]
	at io.cucumber.junit.Cucumber$RunBeforeAllHooks.evaluate(Cucumber.java:266) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at io.cucumber.junit.Cucumber$RunAfterAllHooks.evaluate(Cucumber.java:281) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at io.cucumber.junit.Cucumber$StartTestRun.evaluate(Cucumber.java:233) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at io.cucumber.junit.Cucumber$FinishTestRun.evaluate(Cucumber.java:248) ~[cucumber-junit-7.11.0.jar:7.11.0]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) ~[junit-4.13.2.jar:4.13.2]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) ~[junit-rt.jar:na]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) ~[idea_rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) ~[junit-rt.jar:na]
Caused by: java.lang.RuntimeException: Can't start redis server. Check logs for details.
	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:62) ~[embedded-redis-0.7.2.jar:na]
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:39) ~[embedded-redis-0.7.2.jar:na]
	at redis.embedded.RedisServer.start(RedisServer.java:9) ~[embedded-redis-0.7.2.jar:na]
	at dreamdiary.support.redis.EmbeddedRedisConfig.redisServer(EmbeddedRedisConfig.java:26) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.22.jar:5.3.22]
	... 57 common frames omitted
```

# 코드 분석
## 에러 발생 시점
`embedded-redis-0.7.2.jar` 안의 `AbstractRedisInstance`에서 `awaitRedisServerReady()`를 호출하면서 발생합니다.

## 코드 흐름
[EmbeddedRedisConfig.java](https://github.com/9o-clock/9o-clock-server/blob/cf68d81493a502bff45e149584c83c8390f7e6b3/src/main/java/dreamdiary/support/redis/EmbeddedRedisConfig.java#L23) redis server를 실행시킵니다.

여기서 운영체제를 구분하여(`isArmMac()`), ArmMac은 resource 폴더 안의 redis-server 바이너리 실행 파일을, 그게 아니면 라이브러리 기본 생성자에 의해 실행파일을 링크합니다.
호출 순서는 `new RedisServer()` -> `RedisServerBuilder()` -> `RedisExecProvider` -> `RedisExecProvider.defaultProvider()`입니다.
![defaultProvider](https://github.com/9o-clock/9o-clock-server/assets/105261571/942b8b22-a51e-46e9-a2ca-98be43da3e5c)

windows 환경에 따라 '.exe' 파일을 설정합니다.
[redisServer.start()](https://github.com/9o-clock/9o-clock-server/blob/cf68d81493a502bff45e149584c83c8390f7e6b3/src/main/java/dreamdiary/support/redis/EmbeddedRedisConfig.java#L26)을 호출하여 서버를 가동합니다. 이 때 내부에서는 `createRedisProcessBuilder().start()`를 호출하여 실제 실행 파일을 실행시킵니다.

![redis를위한param확인](https://github.com/9o-clock/9o-clock-server/assets/105261571/3ac224ee-2ced-4dd5-b164-6b226bf8e2c6)
이미지 상의 39번 라인에서 서버 상태를 점검하기 위해 `awaitRedisServerReady()`를 호출합니다.

![awaitRedisServerReady](https://github.com/9o-clock/9o-clock-server/assets/105261571/e665ea79-d20c-432d-940b-0923c15c806a)
주석 줄처럼, redis 서버가 활성화되기 이전에 stream이 종료되면서 익셉션을 반환합니다.

**Comment by PCloud63514** [comment]
윈도우 환경에서 실행했지만 해당 에러를 발견하지 못했습니다.
로그를 더 제공해주세요~

**Comment by leesj8116** [comment]
원인이 명확하지 않으며, 특정 개인 환경 문제일 가능성이 크므로 Close 하겠습니다!
